# Generated by Django 4.1 on 2022-08-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['join_date'],
            },
        ),
    ]
