# Generated by Django 4.1 on 2022-08-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_members_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
