# Generated by Django 4.1 on 2022-08-28 22:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
